### ISSUE TITLE
how to download project from here

### ISSUE THREAD

**Issue by bilal2-1** [google-developer-training/android-advanced-starter-apps#1]

**Comment by zawawimanja** [comment]
on the right side, there is clone or download button which is in green color.

**Comment by GeneAndGoogle** [comment]
As @zawawimanja noted, click the green **Clone or Download** button under the **Code** tab. You can either download it using git or download a .zip file.
![Screen Shot 2020-02-14 at 1 43 27 PM](https://user-images.githubusercontent.com/54457695/74569861-47368000-4f30-11ea-977a-c422dea8696a.png)
